# Generated by Django 2.2.5 on 2019-10-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_default_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_interval', models.IntegerField(default=15)),
                ('last_output_time', models.DateTimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SimpleOutput')),
            ],
        ),
    ]
