# Generated by Django 2.2.5 on 2019-09-30 09:57

from django.db import migrations
from dashboard.models import MODERATOR_ONLY, DISABLED

admin_commands = [('!setgame', MODERATOR_ONLY),
                  ('!addcom', DISABLED),
                  ('!delcom', DISABLED),
                  ('!editcom', DISABLED),
                  ('!alias', DISABLED),
                 ]

def create_admin_commands(apps, schema_editor):
    Command = apps.get_model('dashboard', 'Command')

    commands = []
    for admin_command in admin_commands:
        cmd = Command(command=admin_command[0], permissions=admin_command[1], invocation_count=0, is_built_in=True, output=None)
        commands.append(cmd)

    Command.objects.bulk_create(commands)

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_timedmessage'),
    ]

    operations = [
        migrations.RunPython(create_admin_commands),
    ]
