# Generated by Django 2.2.5 on 2019-10-14 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_create_admin_commands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('attempt_number', models.IntegerField(default=1)),
                ('game_setting', models.CharField(max_length=200)),
                ('last_run_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_run_output', to='dashboard.SimpleOutput')),
                ('how_far_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='how_far_output', to='dashboard.SimpleOutput')),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('time_of_death', models.DateTimeField(default=django.utils.timezone.now)),
                ('respect_count', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Run')),
            ],
        ),
    ]
