# Generated by Django 2.2.5 on 2019-10-14 23:53

from django.db import migrations

def create_default_run(apps, schema_editor):
    Run = apps.get_model('dashboard', 'Run')

    default_run = Run(name='(default)', game_setting='Pokemon Ultra Sun')
    default_run.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_death_run'),
    ]

    operations = [
        migrations.RunPython(create_default_run),
    ]
