# Generated by Django 2.2.5 on 2019-10-17 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_broadcaster', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_subscriber', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
