# Generated by Django 2.2.5 on 2019-11-03 13:51

from django.db import migrations
from dashboard.models import DISABLED

def create_uptime_command(apps, schema_editor):
    Command = apps.get_model('dashboard', 'Command')

    cmd = Command(command='!uptime', permissions=DISABLED, invocation_count=0, is_built_in=True, cooldown=True, output=None)
    cmd.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_death_attempt'),
    ]

    operations = [
        migrations.RunPython(create_uptime_command),
    ]
