# Generated by Django 2.2.5 on 2019-11-03 19:59

from django.db import migrations, models
from django.utils.timezone import now

def coins_per_minute_setting(apps, schema_editor):
    Setting = apps.get_model('dashboard', 'Setting')

    setting_object = Setting(key='Coins Per Minute', value='0')
    setting_object.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_uptime_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('coins', models.IntegerField(default=0)),
                ('last_daily', models.DateTimeField(default=now)),
                ('has_won', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(coins_per_minute_setting),
    ]
