# Generated by Django 2.2.5 on 2019-11-05 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_coin_commands'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prize_coins', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Resolved'), (4, 'Cancelled')], default=1)),
                ('open_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('resolved_timestamp', models.DateTimeField(blank=True, null=True)),
                ('cancelled_timestamp', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(max_length=200)),
                ('num_winners', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.BettingEvent')),
            ],
        ),
    ]
