# Generated by Django 2.2.5 on 2019-11-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_bet_bettingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedmessage',
            name='stream_status',
            field=models.IntegerField(choices=[(1, 'Unspecified'), (2, 'Online Only'), (3, 'Offline Only')], default=1),
        ),
    ]
