# Generated by Django 2.2.5 on 2019-11-06 12:08

from django.db import migrations
from dashboard.models import DISABLED

def create_listruns_command(apps, schema_editor):
    Command = apps.get_model('dashboard', 'Command')

    cmd = Command(command='!listruns', permissions=DISABLED, invocation_count=0, is_built_in=True, cooldown=False, output=None)
    cmd.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_timedmessage_stream_status'),
    ]

    operations = [
        migrations.RunPython(create_listruns_command),
    ]
