# Generated by Django 2.2.5 on 2019-11-13 00:02

from django.db import migrations

def set_default_game_gen_8(apps, schema_editor):
    Setting = apps.get_model('dashboard', 'Setting')

    setting_object = Setting.objects.get(key='Current Game')
    setting_object.value = 'Pokemon Sword'
    setting_object.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_listruns_command'),
    ]

    operations = [
        migrations.RunPython(set_default_game_gen_8),
    ]
