# Generated by Django 2.2.5 on 2019-12-11 12:08

from django.db import migrations
from dashboard.models import MODERATOR_ONLY

def create_debug_command(apps, schema_editor):
    Command = apps.get_model('dashboard', 'Command')

    cmd = Command(command='!debug', permissions=MODERATOR_ONLY, invocation_count=0, is_built_in=True, cooldown=False, output=None)
    cmd.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_shoutout_command'),
    ]

    operations = [
        migrations.RunPython(create_debug_command),
    ]
