# Generated by Django 2.2.5 on 2020-01-03 19:50

from django.db import migrations
from dashboard.models import MODERATOR_ONLY, EVERYONE

def create_affliction_commands(apps, schema_editor):
    Command = apps.get_model('dashboard', 'Command')

    cmd = Command(command='!afflict', permissions=MODERATOR_ONLY, invocation_count=0, is_built_in=True, cooldown=False, output=None)
    cmd.save()

    cmd = Command(command='!check', permissions=EVERYONE, invocation_count=0, is_built_in=True, cooldown=True, output=None)
    cmd.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_afflictedpokemon_affliction'),
    ]

    operations = [
        migrations.RunPython(create_affliction_commands),
    ]
