# Generated by Django 2.2.8 on 2020-05-23 06:38

from django.db import migrations
from dashboard.models import DISABLED

def create_song_command(apps, schema_editor):
    Command = apps.get_model('dashboard', 'Command')
    cmd = Command(command="!song", permissions=DISABLED, is_built_in=True, cooldown=False, output=None)
    cmd.save()

def create_lastfm_setting(apps, schema_editor):
    Setting = apps.get_model('dashboard', 'Setting')

    lastfm_apikey_setting = Setting(key='LastFM API Key', value='')
    lastfm_username_setting = Setting(key='LastFM Username', value='')

    lastfm_apikey_setting.save()
    lastfm_username_setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_affliction_commands'),
    ]

    operations = [
        migrations.RunPython(create_song_command),
        migrations.RunPython(create_lastfm_setting)
    ]
