# Generated by Django 3.0.7 on 2020-07-28 11:40

from django.db import migrations
from dashboard.models import MODERATOR_ONLY

def create_tm_commands(apps, schema_editor):
    Command = apps.get_model('dashboard', 'Command')

    lookup_commands = ['!tm', '!hm']

    commands = []
    for lookup_command in lookup_commands:
        cmd = Command(command=lookup_command, permissions=MODERATOR_ONLY, invocation_count=0, is_built_in=True, cooldown=False, output=None)
        commands.append(cmd)

    Command.objects.bulk_create(commands)

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_song_command'),
    ]

    operations = [
        migrations.RunPython(create_tm_commands),
    ]
