# Generated by Django 2.2.8 on 2020-05-23 06:38

from django.db import migrations
from dashboard.models import MODERATOR_ONLY

def create_userbalance_command(apps, schema_editor):
    Command = apps.get_model('dashboard', 'Command')
    cmd = Command(command="!userbalance", permissions=MODERATOR_ONLY, is_built_in=True, cooldown=False, output=None)
    cmd.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_egg_commands'),
    ]

    operations = [
        migrations.RunPython(create_userbalance_command)
    ]
