# Generated by Django 3.0.7 on 2021-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_setslot_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedphrase',
            name='timeout',
            field=models.IntegerField(default=600),
        ),
    ]
